# Generated by Django 6.0.3 on 2026-04-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('LAUNDRY', 'Laundry'), ('CLEANING', 'Cleaning'), ('ELECTRIC', 'Electric Service'), ('TECH', 'Tech Support'), ('OTHER', 'Other Services')], default='OTHER', max_length=50),
        ),
    ]
