# Generated by Django 6.0.3 on 2026-04-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
