# Generated by Django 6.0.3 on 2026-04-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_booking_agent_assigned_booking_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='service_types',
        ),
        migrations.AddField(
            model_name='agent',
            name='categories',
            field=models.ManyToManyField(related_name='agents', to='api.category'),
        ),
    ]
