# Generated by Django 6.0.3 on 2026-05-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_booking_cancellation_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancellation_fee',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='rating',
        ),
        migrations.AddField(
            model_name='booking',
            name='rejection_count',
            field=models.IntegerField(default=0),
        ),
    ]
